---

- name: Install php packages
  become: true
  apt:
          name: [php-fpm, php-gd, php-curl, php-mysql, php-dom, php-xml]
          state: latest
          update_cache: true
          
- name: Configure php-fom with apache2
  become: true
  copy:
          src: files/www.conf
          dest: /etc/php/7.2/fpm/pool.d/

- name: Restart php-fpm
  become: yes
  service:
          name: php7.2-fpm
          state: restarted
